name: Sample Test Pipeline

on:
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test-job:
    name: 'Run Sample Tests'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Checking authorization for Run Workflow action
      - name: Check Authorization
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const authorizers = "${{ secrets.WORKFLOW_RUN_AUTHORIZERS }}".split(",");
            var flag = false;
            for (const authorizer of authorizers) {
              if (authorizer == "${{ github.actor }}") {
                flag = true;
                console.log("${{ github.actor }} has manually triggered workflow run.")
                break;
              }
            }
            if (flag == false) {
              console.error("${{ github.actor }} is not allowed to run workflow manually.");
              process.exit(1);
            }

      # Run sample tests
      - name: Run sample tests
        run: |
          echo "Running sample tests..."
          echo "Sample1 test passed!"
          echo "Sample2 test passed!"
          echo "All sample tests completed successfully!"
